version: '3.8'

services:
  clinica-app:
    build: .
    container_name: clinica-sistema
    ports:
      - "8080:8080"
    volumes:
      - ./database:/app/database  # Para persistir la base de datos
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8080
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
