name: clinica-sistema

services:
- name: clinica-app
  source_dir: /
  github:
    repo: TU_USUARIO/clinica
    branch: main
    deploy_on_push: true
  
  run_command: streamlit run main.py --server.port=8080 --server.address=0.0.0.0
  environment_slug: docker
  instance_count: 1
  instance_size_slug: basic-xxs
  
  envs:
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: STREAMLIT_SERVER_PORT  
    value: "8080"
  - key: STREAMLIT_SERVER_ADDRESS
    value: "0.0.0.0"
  
  http_port: 8080
  
  health_check:
    http_path: "/_stcore/health"
